### ISSUE TITLE
Transcriber to create a manual assignment(s)

### ISSUE THREAD

**Issue by nurifreembd** [FreeUKGen/ComETT#144]
As a transcriber
I need the ability to create multiple manual assignments
so that I can create multiple assignment and transcribe off system images like no images, on paper, local, remote and PDF images.
 

A/C 
Transcriber can create and update a manual assignment and transcribe images that are sourced by them.
User can delete newly created assignment if the record already exist. 
Tool to check for duplicates incase of double entry
User can re-assign to another transcriber - TBC

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Transcriber creates a manual assignment**
  - Given the transcriber is logged in
  - When the transcriber clicks on "Create Manual Assignment" button
  - Then the transcriber can input details like image source, type, and other relevant information
  
- [ ] **Scenario: Transcriber updates a manual assignment**
  - Given the transcriber is logged in
  - When the transcriber clicks on "Edit" for an existing manual assignment
  - Then the transcriber can update details like image source, type, and other relevant information
  
- [ ] **Scenario: Transcriber deletes a manual assignment**
  - Given the transcriber is logged in
  - When the transcriber clicks on "Delete" for an existing manual assignment
  - Then the manual assignment should be removed from the system
  
- [ ] **Scenario: Tool checks for duplicates when creating or updating a manual assignment**
  - Given the transcriber is logged in
  - When the transcriber clicks on "Create" or "Edit" for a manual assignment
  - Then the tool should check if there are any duplicate records and display an error message if found
  
- [ ] **Scenario: Transcriber re-assigns a manual assignment to another user**
  - Given the transcriber is logged in
  - When the transcriber clicks on "Re-Assign" for an existing manual assignment
  - Then the transcriber can select another user to assign the task to

**Comment by Andrew1943** [comment]
Allocate to Advanced User Training
